### Preprocess and Feature Extraction

In [1]:
import pandas as pd
import numpy as np
import os
import re


DATA_PATH = '..\dataset\HW1_M'

### First, we correct the format of the voices

In [2]:
def check_and_extract_metadata(directory):
    metadata_list = []
    incorrect_files = []
    for filename in os.listdir(directory):
        if filename.endswith(".mp3"):
            parts_underline = filename.split(".")[0].split("_")
            parts_dash = filename.split(".")[0].split("-")
            parts_dot = filename.split(".")[0].split(".")
            if(len(parts_underline) == 4):
                parts = parts_underline
            elif(len(parts_dash) == 4):
                parts = parts_dash
            elif(len(parts_dot) == 4):
                parts = parts_dot
            else:
                # print("Error: Incorrect file format for file: ", filename)
                incorrect_files.append(filename)
                continue
            # print(parts)   
            student_id = parts[2]
            question = parts[1]
            gender = parts[3]
            path = os.path.join(directory, filename)
            metadata_list.append({
                "filename": filename,
                "question_number": question,
                "student_id": student_id,
                "gender": gender,
                "path": path
            })
            # return pd.DataFrame(metadata_list)
    return pd.DataFrame(metadata_list) , incorrect_files

metadata_df, incorrect_files = check_and_extract_metadata(DATA_PATH)
metadata_df.head()

,filename,question_number,student_id,gender,path
0,HW1-intro-810103226-male.mp3,intro,810103226,male,..\dataset\HW1_M\HW1-intro-810103226-male.mp3
1,HW1-intro-810801075-male.mp3,intro,810801075,male,..\dataset\HW1_M\HW1-intro-810801075-male.mp3
2,HW1-intro-Student-810101423_male.mp3,intro,Student,810101423_male,..\dataset\HW1_M\HW1-intro-Student-810101423_m...
3,HW1-Q1-810801075-male.mp3,Q1,810801075,male,..\dataset\HW1_M\HW1-Q1-810801075-male.mp3
4,HW1-Q2-810801075-male.mp3,Q2,810801075,male,..\dataset\HW1_M\HW1-Q2-810801075-male.mp3

In [3]:
metadata_df['question_number'].value_counts()

question_number
Q3       108
intro    107
Q4       107
Q5       105
Q2       103
Q1       102
Q6        99
Q2a        3
Q1a        3
Q2b        3
Q1b        3
into       2
Q5b        1
Q1A        1
Q1C        1
Q1B        1
intor      1
Q6a        1
Name: count, dtype: int64

In [4]:
metadata_df['question_number'] = metadata_df['question_number'].apply(lambda x: 'intro' if not x.startswith('Q') else x)

In [5]:
metadata_df['gender'].value_counts()

gender
male                            541
female                          181
Male                             15
MALE                              8
810101423_male                    1
gender                            1
male-converted                    1
male (online-audio-converter      1
male​                             1
male 2                            1
Name: count, dtype: int64

In [6]:
metadata_df['gender'] = metadata_df['gender'].apply(lambda x: 'male' if x == 'Male' or x == 'MALE' else x)

In [7]:
print(metadata_df[metadata_df['gender'] == 'gender'])

                          filename question_number student_id  gender  \
30  HW1_intro_810100206_gender.mp3           intro  810100206  gender

                                               path
30  ..\dataset\HW1_M\HW1_intro_810100206_gender.mp3

In [8]:
print(metadata_df[metadata_df['student_id'] == '810100206'])

                           filename question_number student_id  gender  \
30   HW1_intro_810100206_gender.mp3           intro  810100206  gender
142       HW1_Q1_810100206_male.mp3              Q1  810100206    male
249       HW1_Q2_810100206_male.mp3              Q2  810100206    male
350       HW1_Q3_810100206_male.mp3              Q3  810100206    male
456       HW1_Q4_810100206_male.mp3              Q4  810100206    male
563       HW1_Q5_810100206_male.mp3              Q5  810100206    male
665       HW1_Q6_810100206_male.mp3              Q6  810100206    male

                                                path
30   ..\dataset\HW1_M\HW1_intro_810100206_gender.mp3
142       ..\dataset\HW1_M\HW1_Q1_810100206_male.mp3
249       ..\dataset\HW1_M\HW1_Q2_810100206_male.mp3
350       ..\dataset\HW1_M\HW1_Q3_810100206_male.mp3
456       ..\dataset\HW1_M\HW1_Q4_810100206_male.mp3
563       ..\dataset\HW1_M\HW1_Q5_810100206_male.mp3
665       ..\dataset\HW1_M\HW1_Q6_810100206_male.mp3

In [9]:
metadata_df['gender'] = metadata_df['gender'].apply(lambda x: 'male' if x == 'gender' else x)

In [10]:
metadata_df['gender'].value_counts()

gender
male                            565
female                          181
810101423_male                    1
male-converted                    1
male (online-audio-converter      1
male​                             1
male 2                            1
Name: count, dtype: int64

In [11]:
metadata_df['gender'] = metadata_df['gender'].apply(lambda x: 'female' if x == 'female' else 'male')

In [12]:
metadata_df['gender'].value_counts()

gender
male      570
female    181
Name: count, dtype: int64

In [13]:
# metadata_df['student_id'].filter(metadata_df['student_id'].value_counts() < 6)
metadata_df['student_id'].value_counts()[metadata_df['student_id'].value_counts() < 6].index.tolist()

['810103092',
 '810103344',
 '810103338',
 '810100217',
 '810199459',
 '810102327',
 '810103226',
 '810103136',
 '810103245',
 '810103339',
 '81010',
 '810199319',
 '610399206',
 'Student']

In [14]:
metadata_df[metadata_df['student_id'] == 'Student']

,filename,question_number,student_id,gender,path
2,HW1-intro-Student-810101423_male.mp3,intro,Student,male,..\dataset\HW1_M\HW1-intro-Student-810101423_m...

In [15]:
metadata_df['student_id'] = metadata_df['student_id'].apply(lambda x: '810101423' if x == 'Student' else x)

In [16]:
metadata_df[metadata_df['student_id'] == '81010']

,filename,question_number,student_id,gender,path
94,HW1_intro_81010_male.mp3,intro,81010,male,..\dataset\HW1_M\HW1_intro_81010_male.mp3

In [17]:
metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 751 entries, 0 to 750
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         751 non-null    object
 1   question_number  751 non-null    object
 2   student_id       751 non-null    object
 3   gender           751 non-null    object
 4   path             751 non-null    object
dtypes: object(5)
memory usage: 29.5+ KB

In [18]:
print(len(incorrect_files))

71

In [19]:
metadata_list = []
temp = []
for file in incorrect_files:
    parts_underline = file.split(".")[0].split("_")
    parts_dash = file.split(".")[0].split("-")
    parts_dot = file.split(".")[0].split(".")
    if(len(parts_underline) == 5):
        parts = parts_underline
    elif(len(parts_dash) == 5):
        parts = parts_dash
    elif(len(parts_dot) == 5):
        parts = parts_dot
    else:
        temp.append(file)
        continue
    student_id = parts[3]
    question = parts[1] + '-' + parts[2]
    gender = parts[4]
    path = os.path.join(DATA_PATH, file)
    metadata_list.append({
        "filename": file,
        "question_number": question,
        "student_id": student_id,
        "gender": gender,
        "path": path
    })
    
incorrect_files = temp
metadata_incorect_df = pd.DataFrame(metadata_list)

In [20]:
print(len(incorrect_files))

55

In [21]:
metadata_incorect_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         16 non-null     object
 1   question_number  16 non-null     object
 2   student_id       16 non-null     object
 3   gender           16 non-null     object
 4   path             16 non-null     object
dtypes: object(5)
memory usage: 768.0+ bytes

In [22]:
metadata_incorect_df['question_number'].value_counts()

question_number
Q1-1            1
Q1-2            1
Q1-3            1
Q2-1            1
Q2-2            1
Q2-3            1
Q4-1            1
Q4-2            1
Q4-3            1
Q4-4            1
Q1-a            1
Q1-b            1
Q2-a            1
Q2-b            1
Q3-810199489    1
Q6-610399205    1
Name: count, dtype: int64

In [23]:
metadata_incorect_df[metadata_incorect_df['question_number'] == 'Q3-810199489' ]

,filename,question_number,student_id,gender,path
14,HW1_Q3_810199489_female_3.mp3,Q3-810199489,female,3,..\dataset\HW1_M\HW1_Q3_810199489_female_3.mp3

In [24]:
metadata_incorect_df[metadata_incorect_df['question_number'] == 'Q6-610399205']

,filename,question_number,student_id,gender,path
15,HW1_Q6_610399205_male_2.mp3,Q6-610399205,male,2,..\dataset\HW1_M\HW1_Q6_610399205_male_2.mp3

In [25]:
# metadata_incorect_df['question_number'] = metadata_df['question_number'].apply(lambda x: 'Q3' if x == 'Q3-810199489' else x) 
for index, data in metadata_incorect_df.iterrows():
    if data['question_number'] == 'Q3-810199489':
        metadata_incorect_df.at[index, 'question_number'] = 'Q3'
        metadata_incorect_df.at[index, 'student_id'] = '810199489'
        metadata_incorect_df.at[index, 'gender'] = 'female'
    if data['question_number'] == 'Q6-610399205':
        metadata_incorect_df.at[index, 'question_number'] = 'Q6'
        metadata_incorect_df.at[index, 'student_id'] = '610399205'
        metadata_incorect_df.at[index, 'gender'] = 'male'

In [26]:
metadata_incorect_df['gender'].value_counts()

gender
male      15
female     1
Name: count, dtype: int64

In [27]:
metadata_incorect_df['student_id'].value_counts()

student_id
810103226    10
810103092     4
810199489     1
610399205     1
Name: count, dtype: int64

In [28]:
metadata_df = pd.concat([metadata_df, metadata_incorect_df], ignore_index=True)

In [29]:
metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         767 non-null    object
 1   question_number  767 non-null    object
 2   student_id       767 non-null    object
 3   gender           767 non-null    object
 4   path             767 non-null    object
dtypes: object(5)
memory usage: 30.1+ KB

In [30]:
print(incorrect_files)

['HW1.Q1.810102087_female.mp3', 'HW1.Q1b.810102087_female.mp3', 'HW1.Q1j.810102087_female.mp3', 'HW1.Q2b.810102087_female.mp3', 'HW1.Q4a.810102087_female.mp3', 'HW1.Q4c.810102087_female.mp3', 'HW1.Q4ch.810102087_female.mp3', 'HW1.Q4j.810102087_female.mp3', 'HW1_Intro_810100217.mp3', 'HW1_intro_810103306.mp3', 'HW1_intro_810103345.mp3', 'HW1_Q1.1_810199459_male.mp3', 'HW1_Q1.2_810199459_male.mp3', 'HW1_Q1_610399206.mp3', 'HW1_Q1_810103136.mp3', 'HW1_Q1_810103245.mp3', 'HW1_Q1_810103339.mp3', 'HW1_Q1_810199319.mp3', 'HW1_Q1_Student-810101423.mp3', 'HW1_Q2.1_810199459_male.mp3', 'HW1_Q2.2_810199459_male.mp3', 'HW1_Q2_610399206.mp3', 'HW1_Q2_810103136.mp3', 'HW1_Q2_810103245.mp3', 'HW1_Q2_810103339.mp3', 'HW1_Q2_810199319.mp3', 'HW1_Q2_Student-810101423.mp3', 'HW1_Q3_610399206.mp3', 'HW1_Q3_810103136.mp3', 'HW1_Q3_810103245.mp3', 'HW1_Q3_810103339.mp3', 'HW1_Q3_810199319.mp3', 'HW1_Q3_Student-810101423.mp3', 'HW1_Q4.1_810199459_male.mp3', 'HW1_Q4.2_810199459_male.mp3', 'HW1_Q4.3_810199459_male.mp3', 'HW1_Q4_610399206.mp3', 'HW1_Q4_810103136.mp3', 'HW1_Q4_810103245.mp3', 'HW1_Q4_810103339.mp3', 'HW1_Q4_810199319.mp3', 'HW1_Q4_Student-810101423.mp3', 'HW1_Q5_610399206.mp3', 'HW1_Q5_810103106-male.mp3', 'HW1_Q5_810103136.mp3', 'HW1_Q5_810103245.mp3', 'HW1_Q5_810103339.mp3', 'HW1_Q5_810199319.mp3', 'HW1_Q5_Student-810101423.mp3', 'HW1_Q6_610399206.mp3', 'HW1_Q6_810103136.mp3', 'HW1_Q6_810103245.mp3', 'HW1_Q6_810103339.mp3', 'HW1_Q6_810199319.mp3', 'HW1_Q6_Student-810101423.mp3']

In [31]:
metadata_list = []
temp = []
for file in incorrect_files:
    parts = re.split(r"[._-]+", file)
    # print(parts)
    if len(parts) != 4:
        temp.append(file)
        continue
    student_id = parts[2]
    question = parts[1]
    gender = 'NA'
    path = os.path.join(DATA_PATH, file)
    metadata_list.append({
        "filename": file,
        "question_number": question,
        "student_id": student_id,
        "gender": gender,
        "path": path
    })
    
incorrect_files = temp
metadata_incorect_df = pd.DataFrame(metadata_list)

In [32]:
print(len(incorrect_files))

22

In [33]:
metadata_incorect_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         33 non-null     object
 1   question_number  33 non-null     object
 2   student_id       33 non-null     object
 3   gender           33 non-null     object
 4   path             33 non-null     object
dtypes: object(5)
memory usage: 1.4+ KB

In [34]:
metadata_incorect_df['question_number'].value_counts()

question_number
Q1       5
Q2       5
Q3       5
Q4       5
Q5       5
Q6       5
intro    2
Intro    1
Name: count, dtype: int64

In [35]:
metadata_incorect_df['student_id'].value_counts()

student_id
610399206    6
810103136    6
810103245    6
810103339    6
810199319    6
810100217    1
810103306    1
810103345    1
Name: count, dtype: int64

In [36]:
metadata_incorect_df['gender'].value_counts()

gender
NA    33
Name: count, dtype: int64

In [37]:
metadata_incorect_df.head(10)

,filename,question_number,student_id,gender,path
0,HW1_Intro_810100217.mp3,Intro,810100217,NA,..\dataset\HW1_M\HW1_Intro_810100217.mp3
1,HW1_intro_810103306.mp3,intro,810103306,NA,..\dataset\HW1_M\HW1_intro_810103306.mp3
2,HW1_intro_810103345.mp3,intro,810103345,NA,..\dataset\HW1_M\HW1_intro_810103345.mp3
3,HW1_Q1_610399206.mp3,Q1,610399206,NA,..\dataset\HW1_M\HW1_Q1_610399206.mp3
4,HW1_Q1_810103136.mp3,Q1,810103136,NA,..\dataset\HW1_M\HW1_Q1_810103136.mp3
5,HW1_Q1_810103245.mp3,Q1,810103245,NA,..\dataset\HW1_M\HW1_Q1_810103245.mp3
6,HW1_Q1_810103339.mp3,Q1,810103339,NA,..\dataset\HW1_M\HW1_Q1_810103339.mp3
7,HW1_Q1_810199319.mp3,Q1,810199319,NA,..\dataset\HW1_M\HW1_Q1_810199319.mp3
8,HW1_Q2_610399206.mp3,Q2,610399206,NA,..\dataset\HW1_M\HW1_Q2_610399206.mp3
9,HW1_Q2_810103136.mp3,Q2,810103136,NA,..\dataset\HW1_M\HW1_Q2_810103136.mp3

In [38]:
metadata_df = pd.concat([metadata_df, metadata_incorect_df], ignore_index=True)

In [39]:
metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         800 non-null    object
 1   question_number  800 non-null    object
 2   student_id       800 non-null    object
 3   gender           800 non-null    object
 4   path             800 non-null    object
dtypes: object(5)
memory usage: 31.4+ KB

In [40]:
print(incorrect_files)

['HW1.Q1.810102087_female.mp3', 'HW1.Q1b.810102087_female.mp3', 'HW1.Q1j.810102087_female.mp3', 'HW1.Q2b.810102087_female.mp3', 'HW1.Q4a.810102087_female.mp3', 'HW1.Q4c.810102087_female.mp3', 'HW1.Q4ch.810102087_female.mp3', 'HW1.Q4j.810102087_female.mp3', 'HW1_Q1.1_810199459_male.mp3', 'HW1_Q1.2_810199459_male.mp3', 'HW1_Q1_Student-810101423.mp3', 'HW1_Q2.1_810199459_male.mp3', 'HW1_Q2.2_810199459_male.mp3', 'HW1_Q2_Student-810101423.mp3', 'HW1_Q3_Student-810101423.mp3', 'HW1_Q4.1_810199459_male.mp3', 'HW1_Q4.2_810199459_male.mp3', 'HW1_Q4.3_810199459_male.mp3', 'HW1_Q4_Student-810101423.mp3', 'HW1_Q5_810103106-male.mp3', 'HW1_Q5_Student-810101423.mp3', 'HW1_Q6_Student-810101423.mp3']

In [41]:
metadata_list = []
temp = []
for file in incorrect_files:
    parts = re.split(r"[._-]+", file)
    # print(parts)
    if len(parts) != 5:
        temp.append(file)
        continue
    student_id = parts[2]
    question = parts[1]
    gender = parts[3]
    path = os.path.join(DATA_PATH, file)
    metadata_list.append({
        "filename": file,
        "question_number": question,
        "student_id": student_id,
        "gender": gender,
        "path": path
    })
    
incorrect_files = temp
metadata_incorect_df = pd.DataFrame(metadata_list)

In [42]:
print(len(incorrect_files))

7

In [43]:
print(incorrect_files)

['HW1_Q1.1_810199459_male.mp3', 'HW1_Q1.2_810199459_male.mp3', 'HW1_Q2.1_810199459_male.mp3', 'HW1_Q2.2_810199459_male.mp3', 'HW1_Q4.1_810199459_male.mp3', 'HW1_Q4.2_810199459_male.mp3', 'HW1_Q4.3_810199459_male.mp3']

In [44]:
metadata_incorect_df.head(10)

,filename,question_number,student_id,gender,path
0,HW1.Q1.810102087_female.mp3,Q1,810102087,female,..\dataset\HW1_M\HW1.Q1.810102087_female.mp3
1,HW1.Q1b.810102087_female.mp3,Q1b,810102087,female,..\dataset\HW1_M\HW1.Q1b.810102087_female.mp3
2,HW1.Q1j.810102087_female.mp3,Q1j,810102087,female,..\dataset\HW1_M\HW1.Q1j.810102087_female.mp3
3,HW1.Q2b.810102087_female.mp3,Q2b,810102087,female,..\dataset\HW1_M\HW1.Q2b.810102087_female.mp3
4,HW1.Q4a.810102087_female.mp3,Q4a,810102087,female,..\dataset\HW1_M\HW1.Q4a.810102087_female.mp3
5,HW1.Q4c.810102087_female.mp3,Q4c,810102087,female,..\dataset\HW1_M\HW1.Q4c.810102087_female.mp3
6,HW1.Q4ch.810102087_female.mp3,Q4ch,810102087,female,..\dataset\HW1_M\HW1.Q4ch.810102087_female.mp3
7,HW1.Q4j.810102087_female.mp3,Q4j,810102087,female,..\dataset\HW1_M\HW1.Q4j.810102087_female.mp3
8,HW1_Q1_Student-810101423.mp3,Q1,Student,810101423,..\dataset\HW1_M\HW1_Q1_Student-810101423.mp3
9,HW1_Q2_Student-810101423.mp3,Q2,Student,810101423,..\dataset\HW1_M\HW1_Q2_Student-810101423.mp3

In [45]:
metadata_incorect_df['question_number'].value_counts()

question_number
Q1      2
Q5      2
Q1b     1
Q1j     1
Q2b     1
Q4a     1
Q4c     1
Q4ch    1
Q4j     1
Q2      1
Q3      1
Q4      1
Q6      1
Name: count, dtype: int64

In [46]:
metadata_incorect_df['student_id'].value_counts()

student_id
810102087    8
Student      6
810103106    1
Name: count, dtype: int64

In [47]:
print(metadata_incorect_df[metadata_incorect_df['student_id'] == 'Student'])

                        filename question_number student_id     gender  \
8   HW1_Q1_Student-810101423.mp3              Q1    Student  810101423
9   HW1_Q2_Student-810101423.mp3              Q2    Student  810101423
10  HW1_Q3_Student-810101423.mp3              Q3    Student  810101423
11  HW1_Q4_Student-810101423.mp3              Q4    Student  810101423
13  HW1_Q5_Student-810101423.mp3              Q5    Student  810101423
14  HW1_Q6_Student-810101423.mp3              Q6    Student  810101423

                                             path
8   ..\dataset\HW1_M\HW1_Q1_Student-810101423.mp3
9   ..\dataset\HW1_M\HW1_Q2_Student-810101423.mp3
10  ..\dataset\HW1_M\HW1_Q3_Student-810101423.mp3
11  ..\dataset\HW1_M\HW1_Q4_Student-810101423.mp3
13  ..\dataset\HW1_M\HW1_Q5_Student-810101423.mp3
14  ..\dataset\HW1_M\HW1_Q6_Student-810101423.mp3

In [48]:
metadata_incorect_df['student_id'] = metadata_incorect_df['student_id'].apply(lambda x: '810101423' if x == 'Student' else x)

In [49]:
metadata_incorect_df['student_id'].value_counts()

student_id
810102087    8
810101423    6
810103106    1
Name: count, dtype: int64

In [50]:
metadata_incorect_df['gender'].value_counts()

gender
female       8
810101423    6
male         1
Name: count, dtype: int64

In [51]:
metadata_incorect_df['gender'] = metadata_incorect_df['gender'].apply(lambda x: 'male' if x == '810101423' else x)

In [52]:
metadata_incorect_df['gender'].value_counts()

gender
female    8
male      7
Name: count, dtype: int64

In [53]:
metadata_df = pd.concat([metadata_df, metadata_incorect_df], ignore_index=True)

In [54]:
metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815 entries, 0 to 814
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         815 non-null    object
 1   question_number  815 non-null    object
 2   student_id       815 non-null    object
 3   gender           815 non-null    object
 4   path             815 non-null    object
dtypes: object(5)
memory usage: 32.0+ KB

In [55]:
print(incorrect_files)

['HW1_Q1.1_810199459_male.mp3', 'HW1_Q1.2_810199459_male.mp3', 'HW1_Q2.1_810199459_male.mp3', 'HW1_Q2.2_810199459_male.mp3', 'HW1_Q4.1_810199459_male.mp3', 'HW1_Q4.2_810199459_male.mp3', 'HW1_Q4.3_810199459_male.mp3']

In [56]:
metadata_list = []
temp = []
for file in incorrect_files:
    parts = re.split(r"[._-]+", file)
    # print(parts)
    if len(parts) != 6:
        temp.append(file)
        continue
    student_id = parts[3]
    question = parts[1] + '-' + parts[2] 
    gender = parts[4]
    path = os.path.join(DATA_PATH, file)
    metadata_list.append({
        "filename": file,
        "question_number": question,
        "student_id": student_id,
        "gender": gender,
        "path": path
    })
    
incorrect_files = temp
metadata_incorect_df = pd.DataFrame(metadata_list)

In [57]:
print(len(incorrect_files))

0

In [58]:
metadata_incorect_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         7 non-null      object
 1   question_number  7 non-null      object
 2   student_id       7 non-null      object
 3   gender           7 non-null      object
 4   path             7 non-null      object
dtypes: object(5)
memory usage: 408.0+ bytes

In [59]:
metadata_incorect_df['question_number'].value_counts()

question_number
Q1-1    1
Q1-2    1
Q2-1    1
Q2-2    1
Q4-1    1
Q4-2    1
Q4-3    1
Name: count, dtype: int64

In [60]:
metadata_incorect_df['student_id'].value_counts()

student_id
810199459    7
Name: count, dtype: int64

In [61]:
metadata_incorect_df['gender'].value_counts()

gender
male    7
Name: count, dtype: int64

In [62]:
metadata_df = pd.concat([metadata_df, metadata_incorect_df], ignore_index=True)

In [63]:
metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 822 entries, 0 to 821
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         822 non-null    object
 1   question_number  822 non-null    object
 2   student_id       822 non-null    object
 3   gender           822 non-null    object
 4   path             822 non-null    object
dtypes: object(5)
memory usage: 32.2+ KB

In [64]:
metadata_df['question_number'].value_counts()

question_number
Q3       115
Q4       113
intro    112
Q5       112
Q2       109
Q1       109
Q6       106
Q1b        4
Q2b        4
Q2a        3
Q1a        3
Q1-2       2
Q2-1       2
Q4-3       2
Q4-2       2
Q4-1       2
Q1-1       2
Q2-2       2
Q2-b       1
Q4c        1
Q4ch       1
Intro      1
Q1j        1
Q1-b       1
Q4a        1
Q2-a       1
Q1-3       1
Q1-a       1
Q4-4       1
Q2-3       1
Q6a        1
Q5b        1
Q1C        1
Q1B        1
Q1A        1
Q4j        1
Name: count, dtype: int64

In [65]:
metadata_df['question_number'] = metadata_df['question_number'].apply(lambda x: 'intro' if not x.startswith('Q') else x)

In [66]:
metadata_df['question_number'].value_counts()

question_number
Q3       115
intro    113
Q4       113
Q5       112
Q1       109
Q2       109
Q6       106
Q1b        4
Q2b        4
Q1a        3
Q2a        3
Q4-3       2
Q4-2       2
Q4-1       2
Q2-2       2
Q2-1       2
Q1-2       2
Q1-1       2
Q1-3       1
Q4ch       1
Q4c        1
Q4a        1
Q1j        1
Q2-b       1
Q2-a       1
Q1-b       1
Q1-a       1
Q4-4       1
Q1A        1
Q1B        1
Q1C        1
Q2-3       1
Q5b        1
Q6a        1
Q4j        1
Name: count, dtype: int64

In [67]:
metadata_df['gender'].value_counts()

gender
male      599
female    190
NA         33
Name: count, dtype: int64

In [68]:
metadata_df['student_id'].value_counts()

student_id
810103226    12
810199459    11
810103262    10
810103145     9
810199569     9
             ..
810101471     6
810103344     5
810103338     5
810102327     4
81010         1
Name: count, Length: 118, dtype: int64

In [69]:
NA_student_numbers = metadata_df['student_id'][metadata_df['gender'] == 'NA'].value_counts().index.tolist()
print(NA_student_numbers)

['610399206', '810103136', '810103245', '810103339', '810199319', '810100217', '810103306', '810103345']

In [70]:
genders = []
for number in NA_student_numbers:
    for index, data in metadata_df.iterrows():
        if data['student_id'] == number and data['gender'] != 'NA':
            genders.append(data['gender'])
            break
print(genders)

['male', 'male', 'male', 'male', 'male', 'male', 'male', 'male']

In [71]:
metadata_df['gender'] = metadata_df['gender'].apply(lambda x: 'male' if x == 'NA' else x)

In [72]:
metadata_df['gender'].value_counts()

gender
male      632
female    190
Name: count, dtype: int64

In [73]:
metadata_df['student_id'].value_counts()[metadata_df['student_id'].value_counts() < 4].index.tolist()

['81010']

In [74]:
print(metadata_df[metadata_df['student_id'] == '81010'])

                    filename question_number student_id gender  \
94  HW1_intro_81010_male.mp3           intro      81010   male

                                         path
94  ..\dataset\HW1_M\HW1_intro_81010_male.mp3

In [75]:
all_students = metadata_df['student_id'].value_counts().index.tolist()
intro_students = metadata_df['student_id'][metadata_df['question_number'] == 'intro'].value_counts().index.tolist()
print(len(all_students), len(intro_students))
print(set(all_students) - set(intro_students))

118 112
{'810102559', '810102087', '810102027', '810103022', '810600125', '810103264'}

In [76]:
metadata_df['student_id'] = metadata_df['student_id'].apply(lambda x: 'invalid' if x == '81010' else x)

In [77]:
metadata_df['has_intro'] = metadata_df['student_id'].apply(lambda x: 1 if x in intro_students else 0)

In [78]:
metadata_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 822 entries, 0 to 821
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   filename         822 non-null    object
 1   question_number  822 non-null    object
 2   student_id       822 non-null    object
 3   gender           822 non-null    object
 4   path             822 non-null    object
 5   has_intro        822 non-null    int64
dtypes: int64(1), object(5)
memory usage: 38.7+ KB

In [79]:
metadata_df.to_csv('metadata.csv', index=False)